version: "3.1"
# The server profiles used in this example are intended for use with edge versions of the product image only.

services:
  pingfederate:
    image: pingidentity/pingfederate:${PING_IDENTITY_DEVOPS_TAG}
    environment:
      - SERVER_PROFILE_URL=https://github.com/gregg303/af
      - SERVER_PROFILE_PATH=server-profiles/af-wf/pingfederate
      - PING_IDENTITY_ACCEPT_EULA=YES
      - VERBOSE=false
      - OPERATIONAL_MODE=STANDALONE
      - PF_BASE_HOST=localhost
      - PF_BASE_PORT=9031
      - PF_ADMIN_PORT=9999

    env_file:
      # Configuration file created when setup.sh (Getting-started project root directory) is first run to source
      # devops user/key details for evaluation licenses and for docker image/git tags
      - ~/.pingidentity/devops
    # Example: Examples below for mounting local directories for inbound server profile and persisting
    #          server build.  The local /opt/out directory must be empty when building new server
    #             /opt/out - Resulting server build
    #             /opt/in  - Inbound server-profile detail in liue of SERVER_PROFILE_URL (must be commented out)
    #volumes:
    #   - ${HOME}/projects/devops/volumes/simple-sync.pingfederate:/opt/out
    #   - ${HOME}/projects/devops/pingidentity-server-profiles/baseline/pingfederate:/opt/in
    ports:
      - 9031:9031
      - 9999:9999
    networks:
      - pingnet

networks:
    pingnet:
